graph TD

n0["Program"]
n1["FunctionDefinition<br/>name=main"]
n2["Block"]
n3["ReturnStatement"]
n4["BinaryOp<br/>op=PERCENT"]
n5["Number<br/>value=5"]
n6["Number<br/>value=3"]

n4 -->|left| n5
n4 -->|right| n6
n3 -->|expr| n4
n2 -->|items.0| n3
n1 -->|body| n2
n0 -->|items.0| n1
